/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package me.redteapot.nametaghider;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
